version: '3.4'

services:
  testcicd:
    image: testcicd
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3600:3600
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
