version: '3.4'

services:
  testcicd:
    image: testcicd
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3600:3600
