name: Linters

on: 
  pull_request:
  push:
    branches: [main]

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Setup ESLint
        run: |
          npm install --save-dev eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin @next/eslint-plugin-next eslint-plugin-react
      - name: Run ESLint
        run: |
          npm run lint